clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  build:
    image: pybuilder
    commands:
      - echo "starting build"
      - pwd
      - echo $HOME
      - id
      - ls -la
      - pip install --trusted-host devpi -r dev-requirements.txt
      - pytest
      - python setup.py sdist bdist_wheel

  resolve:
    image: alpine
    commands:
      - cat /etc/resolv.conf
    when:
      status: [ success, failure ]
