clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  build:
    image: pybuilder
    commands:
      - echo "starting build"
      - pwd
      - echo $HOME
      - id
      - ls -la
      - pip install -r dev-requirements.txt
      - pytest
      - python setup.py sdist bdist_wheel

  deploy:
    image: pybuilder
    commands:
      - echo "uploading to local devpi"
      - devpi use http://devpi:3141
      - devpi login test --password=test
      - devpi use test/dev
      - devpi upload --format sdist,bdist_wheel
        # - twine upload -r devpi dist/*
    when:
      status: [ success ]
