pipeline:

  build:
    image: python:3-slim
    commands:
      - echo "starting build"
      - pip install -r requirements.txt
      - pip install -e .
      - pip install pytest
      - pytest

  resolve:
    image: alpine
    commands:
      - cat /etc/resolv.conf
    when:
      status: [ success, failure ]
