clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  build:
    image: pybuilder
    commands:
      - echo "starting build"
      - pwd
      - echo $HOME
      - id
      - ls -la
      - pip install --trusted-host devpi -r dev-requirements.txt
      - pytest
      - python setup.py sdist bdist_wheel

  deploy:
    image: pybuilder
    commands:
      - echo "uploading to local devpi"
      - devpi use http://devpi:3141
      - devpi user -c testuser password=123
      - devpi loging testuser --password=123
      - devpi index -c dev bases=root/pypi
      - devpi use test/user/dev
      - devpi upload
        # - twine upload -r devpi dist/*
    when:
      status: [ success ]
