clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  deps:
    image: pybuilder
    commands:
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install -r dev-requirements.txt

  test:
    group: qa
    image: pybuilder
    commands:
      - source . .venv/bin/activate
      - pytest

  pylint:
    group: qa
    image: pybuilder
    commands:
      - source . .venv/bin/activate
      - pylint hjs

  doc:
    group: qa
    image: pybuilder
    commands:
      - source . .venv/bin/activate
      - sphinx-build -b html doc/source doc/build

  sonar:
    group: qa
    image: sonar-scanner
    commands:
      - sonar-scanner -X

  deploy:
    image: pybuilder
    commands:
      - echo "uploading to local devpi"
      - devpi use http://devpi:3141
      - devpi login test --password=test
      - devpi use test/dev
      - devpi upload --with-docs --format sdist,bdist_wheel
    when:
      status: [ success ]
