clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  test:
    image: pybuilder
    commands:
      - echo "starting build"
      - pwd
      - echo $HOME
      - id
      - ls -la
      - pip install -r dev-requirements.txt
      - pytest
      - sphinx-build -b html doc/source dist/html

  sonar:
    image: sonar-scanner
    commands:
      sonar-scanner \
      -Dsonar.projectKey=hjs \
      -Dsonar.sources=. \
      -Dsonar.host.url=http://127.0.0.1:9001 \
      -Dsonar.login=fcccb2f14c39d2594d41ee6566f2bd77816c42e1

  deploy:
    image: pybuilder
    commands:
      - echo "uploading to local devpi"
      - devpi use http://devpi:3141
      - devpi login test --password=test
      - devpi use test/dev
      - devpi upload --with-docs --format sdist,bdist_wheel
    when:
      status: [ success ]
