clone:
  git:
    image: plugins/git
    tags: true

pipeline:

  deps:
    image: pybuilder
    commands:
      - pip install -r dev-requirements.txt

  test:
    group: qa
    image: pybuilder
    commands:
      - pip install -r requirements.txt
      - pytest

  pylint:
    group: qa
    image: pybuilder
    commands:
      - pip install -r requirements.txt
      - pylint

  doc:
    group: qa
    image: pybuilder
    commands:
      - sphinx-build -b html doc/source dist/html

  sonar:
    group: qa
    image: sonar-scanner
    commands:
      - sonar-scanner -h
      - sonar-scanner \
          -Dsonar.projectKey=hjs \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://127.0.0.1:9001 \
          -Dsonar.login=fcccb2f14c39d2594d41ee6566f2bd77816c42e1

  deploy:
    image: pybuilder
    commands:
      - echo "uploading to local devpi"
      - devpi use http://devpi:3141
      - devpi login test --password=test
      - devpi use test/dev
      - devpi upload --with-docs --format sdist,bdist_wheel
    when:
      status: [ success ]
