pipeline:

  clone:
    git:
      image: plugins/git
      tags: true

  build:
    image: pybuilder
    commands:
      - echo "starting build"
      - pip install -r requirements.txt
      - pip install pytest
      - pytest
      - python setup.py sdist bdist_wheel

  resolve:
    image: alpine
    commands:
      - cat /etc/resolv.conf
    when:
      status: [ success, failure ]
